### ISSUE TITLE
Use `preferredLocation` for packages entries

### ISSUE THREAD

**Issue by LordTermor** [fhdk/bxtctl#1]
`PackageResponse` have a `preferredLocation` field that should be used as a `poolEntries` key to have a preferred entry (aka candidate).

**Comment by fhdk** [comment]
I am speculating if I somehow overlooked this?

According to the swagger docs - the response model looks like

```
[
  {
    "name": "string",
    "section": "string",
    "poolEntries": {
      "additionalProp1": {
        "version": "string",
        "signaturePath": true
      },
      "additionalProp2": {
        "version": "string",
        "signaturePath": true
      },
      "additionalProp3": {
        "version": "string",
        "signaturePath": true
      }
    },
    "preferredLocation": "string"
  }
]
```

I think we already talked about **signaturePath** being **hasSignature** as boolean

But the property **additionalProp1** appears to have **sync** as it's name when querying the api.

**Comment by LordTermor** [comment]
I'll clear out docs regarding this - additional props are names of pool entries (aka pool locations). Every package can have an entry in "overlay", "sync" and "automated" locations.

The one that's preferred over others and ends up being written into the box is a value of `preferredLocation` field.

**Comment by fhdk** [comment]
```
poetry run bxtctl
TODO - remove this block
---------- PERMISSIONS ---------- 
bxt user: 'default' has access to:
Branches      : {'testing', 'unstable', 'stable'}
Architectures : {'aarch64', 'x86_64'}
Repositories  : {'core', 'extra', 'multilib'}
--------------------------------- 
(default@bxt) $ list core unstable x86_64
{'name': 'qwt', 'section': {'branch': 'unstable', 'repository': 'core', 'architecture': 'x86_64'}, 'poolEntries': {'overlay': {'version': '6.2.0-1', 'hasSignature': True}}, 'preferredLocation': 'overlay'}
(default@bxt) $ 
```

So instead of - in my test - hardcoding the location - it is picked by using the preferredLocation ?

**Comment by fhdk** [comment]
Does that also mean that when adding or changing a package the preferredLocation should be used to target the changes correctly?

**Comment by LordTermor** [comment]
Exactly.

**Comment by fhdk** [comment]
fixed with the latest commit.

**Comment by LordTermor** [comment]
> Does that also mean that when adding or changing a package the preferredLocation should be used to target the changes correctly?

Adding package manually can be done only to overlay. As for deleting we have to decide what behavior is more preferable: can users remove synced/auto-deployed packages or not.
https://github.com/anydistro/bxt/issues/63
